andyearnshaw/Intl.js

src/core.js
The feature test that checked if Object.defineProperty was working
correctly wasn't actually testing that it defined properties. This
caused conflicts with shams in IE 8 and below.
=> Fix Object.defineProperty feature detection

tasks/utils/reduce.js
Solves #90 for `latn` numeric system.
This change will only affect locales whose default numeric system is not latn.  For these locale data files one string will be added into `nu` array in the `number` section in locale data files. For example for `locale-data/json/ar-AE.json` the change will be:
```javascript
"number": {
"nu": [
"arab",
"latn"
],
```
instead of original:
```javascript
"number": {
"nu": [
"arab"
],
```
=> Always include latn numeric system in locale data

tasks/utils/reduce.js
This PR resolves #92
This will hardly have any impact on size of locale data files. In most cases locale data files will become a bit smaller because `narrow` weekdays names tend to be smaller than `short` ones.
=> Use correct width for weekday names

src/cldr.js
Adding missing `src\cldr` file to resolve build issues. I've copied everything prefixed with `$$cldr$$` from `dist/Intl.js` file.
`grunt build` is now successful:
```console
$ grunt build
Running "bundle_jsnext:dest" (bundle_jsnext) task
INFO: Using a global wrapper module for "src/main.js", exporting namespace "IntlPolyfill"
>> Bundled library written in dist/Intl.js
Running "uglify:build" (uglify) task
Running "cjs_jsnext:dest" (cjs_jsnext) task
>> CommonJS library written in tmp/
Running "copy:src" (copy) task
Copied 4 files
Running "concat:complete" (concat) task
File dist/Intl.complete.js created.
Done, without errors.
```
All unit tests pass with dist files generated by `grunt build`.
=> GH95 Trouble building

README.md, index.js, package.json
This will facilitate the optional fetching/execution of the polyfill when using `require.ensure()` in webpack/browerify, e.g.:
```
if (!window.Intl) {
// hello safari
require.ensure(['intl'], (require) => {
window.Intl = require('intl');
// locale data should be also included here...
runMyApp()
}, "IntlBundle");
else {
// hello chrome, ie, etc.!
runMyApp()
}
```
=> fixes #118: ignoring the inclusion of all locale date when bundling the polyfill with browserify/webpack.

index.js
Using `m.default` and `exports.default` was causing issues for IE8.
This syntax should maximize backwards compatibility with older browsers.
=> Fix compatibility with ES3

README.md
When I first read this code, I thought there was a bug and that it ought to be `var IntlPolyfill = require('intl');`
FormatJS guys [pointed out](https://github.com/yahoo/formatjs-site/pull/200/files#r39440912) that `require('intl');` was declaring `IntlPolyfill` as a global variable.
I think this little clarification would be welcome.
=> Clarify polyfill code

src/cldr.js, src/core.js, tasks/utils/reduce.js
- Include short, long and full templates from CLDR as part of the extraction task to combine time and date formats correctly
based on http://unicode.org/reports/tr35/tr35-dates.html#availableFormats_appendItems
- Diverge from spec becuase of bug #58 in ECMA 402 to requested options can overrule best match format as described here:
https://github.com/tc39/ecma402/issues/58
- Refactor the whole CLDR script to complain with the algo described here:
http://unicode.org/reports/tr35/tr35-dates.html#availableFormats_appendItems
=> Refactor CLDR for dates (follow up from PR #145)

src/11.numberformat.js
A small change to fix https://github.com/andyearnshaw/Intl.js/commit/b5d39ad0a3cb502ea1133a9398261e38f20d32d6#commitcomment-16380172
=> fix {percentSign} in FormatNumberToParts

src/12.datetimeformat.js
In the latest version of the spec proposal, we use `literal` instead of `separator`.
=> Switch separator to literal in DateTimeFormat.prototype.formatToParts

src/11.numberformat.js, src/12.datetimeformat.js
This is a fix to the polyfill which follows the update to the `formatToParts` spec as proposed in https://github.com/zbraniecki/ecma402/pull/2/.
=> Unify token matching in Format{DateTime,Number}ToParts

src/12.datetimeformat.js
=> Support era to resolve date string

src/11.numberformat.js
Fixes: https://github.com/andyearnshaw/Intl.js/issues/176.
Basically `for-in` loop iterate over all enumerable properties of the object itself and those the object inherits from its constructor's prototype. In the FormatNumber function, the parts Object is from [List](https://github.com/andyearnshaw/Intl.js/blob/master/src/util.js#L116-L124) and that can be parent Object. To fix it, I think we should add a [`hasOwnProperty` check](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#Examples) into `for-in` loop or use this simple way.
=> Replace for-in with basic for loop in FormatNumber

tests/noderunner.js, tests/polyfilling.js
To fix the error on the CI like the following:
https://travis-ci.org/andyearnshaw/Intl.js/builds/137850735
=> tests: undefined variable "self" should be void 0 in the vm

src/12.datetimeformat.js
Fixes https://github.com/andyearnshaw/Intl.js/issues/152 and https://github.com/andyearnshaw/Intl.js/issues/179.
In the InitializeDateTimeFormat, pattern prop as a `_` is checked by diverging and it will be used when the value is matched.
=> BestFitFormatMatcher: Add new penalty as a pattern

tests/sanity.js
The following test case can be falling depending on the timezone of the machine execute tests(e.g. the error on CI). To fix the red light, let me add a helper function to create a Date object from UTC into the `sanity.js`.
+ https://github.com/andyearnshaw/Intl.js/blob/ec31f6fa2ab5d46fcf671ff5a0f0bc29eafae7c8/tests/sanity.js#L33
=> Add newDateUTC to run the sanity.js on CI

src/util.js
Apparently `Object.defineProperty(obj, 'prototype', { writable: false });` sets `obj.prototype` to `null` in Java7 Rhino JS. Naive version works, so update detection code to check that.
=> Fix defineProperty to work with Java7 Rhino JS

src/8.intl.js
One of the tests262 tests if `Array.prototype.push` is used and it was in Intl.js. Let's fix it :)
=> Don't use Array.prototype.push in getCanonicalLocales

tasks/update-tests.js
This is needed for a couple of the getCanonicalLocales tests
=> Add Test262Error to WRAPPER_START for tests to pass

src/8.intl.js, src/9.negotiation.js, src/util.js
Some more fixes to make us pass all-but-one getCanonicalLocales tests. I had to add `toLength` so that we properly deal with negative lengths etc.
=> More fixes for getCanonicalLocales test262 tests

src/11.numberformat.js, src/12.datetimeformat.js
Fixes Intl.js to pass tests262 for formatToParts
=> Minor fixes to make DateTimeFormat's and NumberFormat's formatToParts pass test262

src/core.js
Passing in the `data.locale` variable will help with debugging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/andyearnshaw/intl.js/232)
=> Pass data.locale to Error message

README.md
…as it has supported `Intl` since version 10 - see https://caniuse.com/#feat=internationalization.
Besides this being incorrect it also gives people a wrong impression about the percentage of their userbase that will actually use the polyfill vs the browser's `Intl`.
=> don't blame Safari
